raystack/proton

odpf/optimus/runtime_service.proto
odpf/optimus/task_plugin.proto

Signed-off-by: Kush Sharma <thekushsharma@gmail.com>

fix(optimus): support multiple subquestion/answer at once in plugins

---

.github/workflows/publish.yml

partially resolves #35 
As of now there is no straight forward way to figure out the sequence ID using the buf CLI.
Leaving that part out we should be good to use `proton` for remote generation of go packages.

ci: push protobuf schemas to buf.build on push to `main` branch

---

odpf/optimus/runtime_service.proto

Add Optimus get replay list rpc & message models.

feat: add optimus replay list

---

odpf/optimus/runtime_service.proto

For Optimus : 
1. Updated the misconfigured api path 
2. Adding host entry with the default port in which server starts.

refactor(optimus): update misconfigured api path for runtime_service.proto

---

odpf/common/v1/service.proto

The purpose of this service is to act as a common way to expose version and build info of our services.
This will also house other common endpoints such as one to get server configurations.

feat: add common service with version endpoint to expose version and other info of the server

---

odpf/optimus/runtime_service.proto

Adding:
- BackupDryRun api path
- BackupDryRunRequest model
- BackupDryRunResponse model
to support dry run backup feature in Optimus

feat(optimus): add dryrun backup api path, request response model

---

odpf/guardian/guardian.proto

Changes with respect to this feature: https://github.com/odpf/guardian/pull/54

feat: remove (soft) resources from db for deleted actual resources in the provider

---

odpf/shield/v1/shield.proto

- Adds org_id while creating the group
- Adds Organization body while fetching the group(s)
- Make org_id obselete

fix: organization body in group

---

odpf/assets/bucket.proto
odpf/assets/common/resource.proto
odpf/assets/dashboard.proto
odpf/assets/group.proto
odpf/assets/job.proto
odpf/assets/table.proto
odpf/assets/topic.proto

feat(assets): update assets metadata

---

odpf/stencil/v1/stencil.proto
odpf/stencil/v1beta1/stencil.proto

BREAKING CHANGE: Modify existing download and upload APIs
Add new CRUD APIs for each namespace, schema and version entities.
Rename "descriptors" to "schema" in URL path

feat!: add/modify stencil APIs

---

odpf/metadata/optimus/v1/job.proto
odpf/optimus/runtime_service.proto

- refactor: fix linter errors in cluster and plugins directory

feat(optimus): fetch job task runtime details

---

odpf/assets/table.proto

- Add several fields in `assets/table/TableProfile` to store table usage stats
- Add `usage_count` as a metric for table usage
- Add `common_join` as a metric for the list of joined tables
- Related [PR](https://github.com/odpf/meteor/pull/271) in meteor

feat(assets): add usage metrics to table profile

---

odpf/stencil/v1beta1/stencil.proto

This is related to https://github.com/odpf/stencil/pull/91

feat(stencil): remove http options for create/get schema data rpcs

---

odpf/shield/v1/shield.proto

Moves path of Shield APIs from `/v1/*` to `/v1beta1/*`

chore: move shield apis to v1beta1

---

odpf/optimus/runtime_service.proto

- Adding configuration field in backup spec
- Add backup detail rpc

feat(optimus): add backup detail rpc

---

odpf/entropy/v1beta1/service.proto

BREAKING CHANGE: 
- make Resource.status an enum type.
- Remove resource from UpdateResourceRequest and add urn and configs only.

fix(entropy)!: use enum for resource status and change UpdateResourceRequest to include only urn and configs.

---

odpf/stencil/v1beta1/stencil.proto

- add RPC call `Search`
- define messages `SearchRequest`, `SearchResponse` and `SearchMeta`

feat(stencil): add support for search API

---

odpf/shield/v1beta1/shield.proto

Proto for shield's list groups of a user API.
Issue https://github.com/odpf/shield/issues/55

feat(shield): add api to list groups of a user

---

odpf/optimus/core/v1beta1/runtime.proto

- https://github.com/odpf/optimus/issues/138

Proposal - 1 : add external http sensor at optimus job dependency

---

odpf/guardian/v1beta1/guardian.proto

need this to accommodate the http endpoints for the change in this guardian PR: https://github.com/odpf/guardian/pull/142

feat(guardian): add new endpoint to update one provider by type and urn

---

odpf/optimus/core/v1beta1/runtime.proto

Implementation: 
https://github.com/odpf/optimus/issues/198

feat(optimus): fetch JobRuns for given date range

---

odpf/optimus/core/v1beta1/backup.proto
odpf/optimus/core/v1beta1/job.proto
odpf/optimus/core/v1beta1/job_run.proto
odpf/optimus/core/v1beta1/job_spec.proto
odpf/optimus/core/v1beta1/namespace.proto
odpf/optimus/core/v1beta1/project.proto
odpf/optimus/core/v1beta1/replay.proto
odpf/optimus/core/v1beta1/resource.proto
odpf/optimus/core/v1beta1/runtime.proto
odpf/optimus/core/v1beta1/secret.proto
odpf/optimus/plugins/v1beta1/cli.proto
odpf/optimus/plugins/v1beta1/dependency_resolver.proto

fix for https://github.com/odpf/optimus/issues/178

refactor(optimus): Split optimus runtime proto

---

odpf/guardian/v1beta1/guardian.proto

* add get provider types api for feature request - https://github.com/odpf/guardian/issues/158
**API Request**:
```GET /v1beta1/providers/types```
**API Response(sample)**:
```json
{
"providers_types": [
{
"name": "bigquery",
"resource_types": [
"table",
"dataset"
]
},
{
"name": "metabase",
"resource_types": [
"group",
"collection",
"database"
]
}
]
}
```
The resource_types field values such as `table`, `dataset` etc will be singular.

feat: Add guardian get provider types request

---

odpf/optimus/core/v1beta1/job_spec.proto

Adding GetDeployJobsStatus RPC and modify RefreshJobsResponse as part of this RFC:
https://github.com/odpf/optimus/blob/main/docs/docs/rfcs/20220216_improving_time_and_flow_of_deployment.md
Specifically for this issue: https://github.com/odpf/optimus/issues/181

feat(optimus): add GetDeployJobsStatus

---

odpf/entropy/v1beta1/service.proto

Updated the resource definitions as per discussions.
* Resource fields are organised into metadata, spec and state (spec = `ResourceSpec`, state = `ResourceState`)
* `UpdateResource` now accepts the `ResourceSpec` completely (which is configs + dependencies)
* `parent` has been renamed to `project`.

refactor(entropy): updated the protobuf definitions

---

odpf/optimus/core/v1beta1/job_spec.proto

GetJobSpecificationsResponse should also include project and namespace name. This model is being used by the ongoing development epic of Optimus, thus not deprecating the replaced field.

feat(optimus): change GetJobSpecificationsResponse to also include project and namespace name

---

odpf/optimus/core/v1beta1/job_spec.proto

Add unknown dependencies field in GetDeployJobsStatusResponse as part of [supporting cross Optimus sensor PR](https://github.com/odpf/optimus/pull/438).

feat(optimus): add unknown_dependencies field in GetDeployJobsStatusResponse

---

odpf/guardian/v1beta1/guardian.proto

Add an API to support Bulk access revocation in the [guardian](https://github.com/odpf/guardian/issues/202).
Sample API:
> curl --location --request POST 'localhost:3000/api/v1beta1/appeals/revoke' 
--header 'X-Auth-Email: vikash.singh@gojek.com' 
--header 'Content-Type: application/json' 
--data-raw '{
"account_id":["vikash.singh@gojek.com", "sushmith.bhatta@gojek.com"],
"reason": "Bulk revoke"
}'

feat: add API for bulk revoke access

---

odpf/assets/v1beta2/asset.proto
odpf/assets/v1beta2/bucket.proto
odpf/assets/v1beta2/dashboard.proto
odpf/assets/v1beta2/job.proto
odpf/assets/v1beta2/table.proto
odpf/assets/v1beta2/topic.proto
odpf/assets/v1beta2/user.proto

The create and update time fields in the Asset proto are meant to track when the asset was first created or updated which would correspond to the first and last time the asset was ingested.
Therefore, add create/update time fields inside specific asset metadata protos:
- Bucket
- Dashboard
- Job
- Table
- Topic
- User
This will track, for example, when a table was created in the database and the last time the table structure was updated.
Related to https://github.com/odpf/meteor/issues/409

feat: support create/update time in asset metadata

---

odpf/assets/v1beta2/common.proto
odpf/assets/v1beta2/experiment.proto
odpf/assets/v1beta2/metric.proto
odpf/assets/v1beta2/ml_feature.proto
odpf/assets/v1beta2/ml_model.proto
odpf/assets/v1beta2/service.proto

For enabling End-to-End lineage, add metadata models for the following:
- Machine Learning(ML) Feature
- ML Model
- Service
- Experiment
- Metric

feat: add metadata models to enable E2E lineage

---

odpf/stencil/v1beta1/stencil.proto

fixing lint issue
```bash
odpf/stencil/v1beta1/stencil.proto:145:24:Field name "Compatibility" should be lower_snake_case, such as "compatibility".
```

fix: lint issue in stencil

---

odpf/compass/v1beta1/service.proto

- The response now includes the node attributes with probes info for
each source and target in the lineage edges.
- Deprecate type and service fields on LineageNode used in
UpsertAssetRequest and UpsertPatchAssetRequest. These fields are no
longer necessary for uniquely identifying an asset - the URN suffices.

feat(compass): add node attributes in CompassService.GetGraph RPC

---

odpf/siren/v1beta1/siren.proto

- Update subscription API
- Generalize alerts API
- Relate with siren's changes https://github.com/odpf/siren/pull/145

refactor(siren): update subscription and generalize alerts api

---

odpf/assets/v1beta2/application.proto
odpf/assets/v1beta2/feature_table.proto

The attributes field was missing in Application and FeatureTable protos.

feat: add attributes field for v1beta2 asset types

---

odpf/compass/v1beta1/service.proto

Add flag in UpsertPatchAssetRequest to explicitly overwrite lineage. It is only applicable when neither upstreams nor downstreams are specified in the patch request.
related to https://github.com/odpf/compass/issues/194

feat: UpsertPatchAsset - allow to overwrite lineage

---

odpf/shield/v1beta1/shield.proto

The following API routes shall go away, as shield now have relation APIs.
RESOURCE
```
AddTeamToResource
AddOwnerToResource
```
GROUP
```
AddUsers 
RemoveUser 
AddAdmins 
RemoveAdmin 
ListGroupUsers 
ListGroupAdmins 
```
ORGANIZATION
```
AddAdmins
RemoveAdmin
```
PROJECT
```
AddAdmins
RemoveAdmin
```

refactor: removed APIs that are replaced by relation APIs

---

odpf/compass/v1beta1/service.proto

* add `include_fields` param in searchAssetsRequest to give user ability to fetch additional fields which are available in the search hits in elasticsearch
Related to: https://github.com/odpf/compass/issues/196

feat(compass): add new field in searchAssetsRequest

---

odpf/compass/v1beta1/service.proto

* Add pagination support in SearchAssets API. `from` would be the offset and `size` would be the page size. The changes are backward compatible

feat(compass): support pagination in SearchAssets

---

odpf/compass/v1beta1/service.proto

Compass is a single-tenant application, to make it multi-tenant just like most `odpf` applications few breaking changes are introduced.

feat: support for namespace in compass

---

raystack/frontier/v1beta1/frontier.proto

- did some breaking changes in query params used to start auth flow
- redirect bool is changed to `redirect_onstart` to make it less ambigious
- `callback_url` is used to override the default callback url specified in frontier configs

feat(frontier): oidc auth callback can be changed using query params

---

raystack/guardian/v1beta1/guardian.proto

- creating tenant details is optional and the database will be migrated with default tenant if the app is used in single tenancy

feat(guardian): namespaces for multi-tenancy

---

raystack/frontier/v1beta1/admin.proto
raystack/frontier/v1beta1/frontier.proto
raystack/frontier/v1beta1/models.proto

- API to have delegated checkout(bypass billing engine)

feat(frontier): APIs to filter projects explicitly added

---

raystack/frontier/v1beta1/frontier.proto

The billing_id in entitlement check is now optional, since it can be inferred on the basis of org id or project id. This PR updates the message validation rules to ensure it is treated as optional.

fix: make billing_id optional in entitlement check request

---

raystack/frontier/v1beta1/admin.proto

Add new fields to `ListAllOrganizationsRequest` and `ListAllOrganizationsResponse` to enable pagination.
Fields added:
`page_size` ,`page_num` to `ListAllOrganizationsRequest` message
`total_pages` to `ListAllOrganizationsResponse` message

feat(frontier):add pagination to ListOrganizations

---

raystack/frontier/v1beta1/admin.proto

Adds pagination to list all invoice API. `page_num` and `page_size` params can be used to modulate the pages. `count` returns the total number of items (not the count of items in response) so that it can be consumed for different logics if needed.

add pagination to list all invoice API

---

raystack/frontier/v1beta1/admin.proto

Negative number works as overdraft

feat(frontier): billing account credit min limit

---

raystack/frontier/v1beta1/admin.proto
raystack/frontier/v1beta1/frontier.proto
raystack/frontier/v1beta1/models.proto

Add proto messages and RPC contract for Org KYC management. 
The Org KYC consists of 3 main fields: 
1. OrgID
2. KYC status (True/False)
3. KYC Doc Link
The GRPC Gateway should expose these endpoints to allow Org KYC management :
1. `get: "/v1beta1/organizations/{org_id}/kyc"`
2. `put: "/v1beta1/admin/organizations/{org_id}/kyc"`

feat(frontier): add Proto for org KYC

---

js/buf.gen.yaml
js/scripts/generate.mjs

This PR exports the entity structs from the `_pb.ts` file.
Currently in the build step, we generate two entity definition files. One is a plain TS struct, and the other is a Message Struct.
We export the plain TS struct in the services index.ts file. Using this plain TS struct in consumer code results in a TS error because the type used in the request and response in the Connect query is the Entity Message struct.
eg If we import the following code from proton
```ts
import type { Organization, GetOrganizationResponse } from '@raystack/proton/frontier
```
The `GetOrganizationResponse.organization` will not satisfy the type of `Organization`
When we build, we create `frontier.ts` and `frontier_pb.ts` files. Both files will have `Organization` structs.
We can't export both, as there will be …

chore: remove old ts exports
