odpf/optimus/hook_plugin.proto
odpf/optimus/task_plugin.proto

Signed-off-by: Kush Sharma <thekushsharma@gmail.com>

feat(optimus): provide job name in plugin while requesting for questions

---

odpf/optimus/runtime_service.proto

add force field to enable Replay force run in Optimus

feat: add force to optimus ReplayRequest

---

.github/workflows/validate.yml

resolves #33 
Refactored validate workflow to use github actions from github.com/bufbuild

ci: use github action from github.com/bufbuild

---

odpf/optimus/cluster/command.proto
odpf/optimus/runtime_service.proto

- These protobufs will be used during raft communication between Optimus server nodes inside the cluster

feat: support for optimus custom scheduler

---

odpf/guardian/guardian.proto

Added a details field to each of the resources of an appeal.

feat: add details to each resource of an appeal

---

odpf/raccoon/EventService.proto

Created GRPC service for raccoon

feat: add event service

---

odpf/shield/v1/shield.proto

Fix: add org_id in project Proto

---

odpf/shield/v1/shield.proto

| Column name      | type     | Example                  |
|------------------|----------|--------------------------|
| id <PK>          | string   | org_manager              |
| name             | string   | Org Manager              |
| types            | []string | ["user" + "group"]       |
| namespace | string   | organization             |
| metadata         | json     | {"resource": "firehose"} |

fix: correct schema for role according to proto

---

odpf/guardian/v1beta1/guardian.proto

- Add filters (query) for ListAppeals and ListUserAppeals

feat(guardian): add list appeals filters

---

odpf/shield/v1beta1/shield.proto

gRPC config for resource authz check, ref: [shield/issues#56](https://github.com/odpf/shield/issues/56)

feat: add rpc for shield authz check

---

odpf/shield/v1beta1/shield.proto

feat: add org_id field for ListGroupsRequest

---

odpf/shield/v1beta1/shield.proto

Ref: https://github.com/odpf/shield/pull/97

feat: add urn for resource

---

odpf/entropy/v1beta1/service.proto

- Add `Create` and `List` providers
- Add `ProviderFilters` to `Resource`

feat: add provider service

---

odpf/optimus/core/v1beta1/job_spec.proto

Replace NamespaceJobs with namespace_names and job_names.

refactor(optimus): restructure RefreshJobsRequest

---

odpf/optimus/core/v1beta1/job_spec.proto

This PR is required to address issue mentioned [here](https://github.com/odpf/optimus/issues/263)

feat: add airflow specific config on job spec

---

odpf/siren/v1beta1/siren.proto

- Update receiver and namespace
- Add a dedicated request/response for each RPC
- Use `data` field as a result placeholder to GET RPC
- Generalize SendNotification rpc

refactor(siren): update receiver and namespace

---

.github/workflows/validate.yml
README.md
buf.lock

- Fix failing CI validate & publish

fix: bump up buf

---

odpf/shield/v1beta1/shield.proto

Update `shield.proto`
Add `limit`, `page`, `keyword` for pagination and filter.

feat(shield): add limit, page, keyword for pagination and filter

---

odpf/entropy/v1beta1/service.proto

For https://github.com/odpf/entropy/issues/70

feat(entropy): add resource history endpoint

---

odpf/siren/v1beta1/siren.proto

related to https://github.com/odpf/siren/issues/100

refactor: remove unnecessary ping handler

---

odpf/guardian/v1beta1/guardian.proto

https://github.com/odpf/guardian/issues/213

feat: add policy appeal options

---

odpf/optimus/core/v1beta1/job_spec.proto
odpf/optimus/core/v1beta1/log_status.proto
odpf/optimus/core/v1beta1/resource.proto
odpf/optimus/core/v1beta1/status.proto

Providing ability for receiving status messages in stream response

refactor(optimus): restructure response proto with log status

---

odpf/entropy/v1beta1/module.proto
odpf/entropy/v1beta1/resource.proto

Adds Module management API definitions as per odpf/entropy#83.

feat(entropy): add module api definitions

---

odpf/optimus/core/v1beta1/job_spec.proto

fixes:  https://github.com/odpf/optimus/issues/512

fix: add Optimus hook lifecycle events for observability

---

odpf/optimus/core/v1beta1/job_run.proto
odpf/optimus/plugins/v1beta1/cli.proto

This PR is to support window versioning, address [here](https://github.com/odpf/optimus/issues/453).

feat: support optimus window versioning

---

odpf/entropy/v1beta1/module.proto

Removes `ModuleSpec` (loader + path) and inlines configs.

feat(entropy): remove path, loader in module

---

odpf/assets/v1beta2/asset.proto
odpf/assets/v1beta2/bucket.proto
odpf/assets/v1beta2/dashboard.proto
odpf/assets/v1beta2/group.proto
odpf/assets/v1beta2/job.proto
odpf/assets/v1beta2/table.proto
odpf/assets/v1beta2/topic.proto
odpf/assets/v1beta2/user.proto
odpf/compass/v1beta1/service.proto

- Move `Asset.attributes` to `(Table | Topic | Job | User | Group | Dashboard).attributes`
- Add `url` to Asset model
- Change type of `labels` from `google.protobuf.Struct` to `map<string, string>`

feat: update asset model

---

odpf/shield/v1beta1/shield.proto

To support metadata key creation for this [shield issue](https://github.com/odpf/shield/issues/162)

feat: add create metadata key API

---

buf.lock

Fixes #183. Sorry again for the inconvenience.

Run `buf mod update`

---

odpf/compass/v1beta1/service.proto

feat(compass): add Upsert API

---

odpf/compass/v1beta1/service.proto

Relates to https://github.com/odpf/compass/issues/170

feat(compass): add CreateAssetProbe

---

odpf/compass/v1beta1/service.proto

Relates to https://github.com/odpf/proton/pull/187#discussion_r974779902

feat(compass): refactor UpsertAsset()

---

odpf/shield/v1beta1/shield.proto

part of [shield#171](https://github.com/odpf/shield/issues/171)
Ref: https://developers.google.com/protocol-buffers/docs/proto#options

fix: depreciate occurrences of nested objects

---

odpf/entropy/v1beta1/resource.proto

feat(entropy): add labels to Update and Action requests

---

odpf/siren/v1beta1/siren.proto

This relates with siren changes [here](https://github.com/odpf/siren/pull/133)

refactor(siren): generalize annotations and labels in cortex post alerts

---

odpf/shield/v1beta1/shield.proto

closes: https://github.com/odpf/shield/issues/178
example of http request for role assignment
```
POST /relations
{
"object_id": "some-sink-xyz",
"object_namespace_id": "entropy_firehose",
"subject": "user:kartik.verma@gojek.com",
"role_name": "owner"
}
Response: 
201 / 409
{
"id": "orn:shield:relation:{{uuid}}",
"object_id": "some-sink-xyz",
"object_namespace_id": "entropy_firehose",
"subject": "user:kartik.verma@gojek.com",
"role_name": "owner"
}
```
refered: https://docs.github.com/en/rest/gists/gists#star-a-gist

feat: rpc & proto for role assignment api

---

odpf/guardian/v1beta1/guardian.proto

https://github.com/odpf/guardian/issues/226

feat(guardian): add appeal config to policy

---

odpf/optimus/core/v1beta1/job_run.proto
odpf/optimus/core/v1beta1/job_spec.proto

needed for :  https://github.com/odpf/optimus/issues/492

feat(optimus) : job explain api

---

odpf/guardian/v1beta1/guardian.proto

- Introduce new field `description` on appeal

feat(guardian): add free text in appeal

---

odpf/assets/v1beta2/application.proto

See https://github.com/odpf/meteor/pull/427#discussion_r1013606211.

refactor!: rename asset {Service => Application}

---

odpf/guardian/v1beta1/guardian.proto

Related issue: https://github.com/odpf/guardian/issues/268

feat: add custom question support

---

odpf/shield/v1beta1/shield.proto

closes: https://github.com/odpf/shield/issues/180

feat: update body schema for check

---

odpf/assets/v1beta2/feature_table.proto

_(an action item from our discussion with CaraML team)_

feat: add desc and type fields to FeatureTable.Entity

---

odpf/guardian/v1beta1/guardian.proto

Related issue: https://github.com/odpf/guardian/issues/128

feat(guardian): support dry run policy & provider

---

odpf/assets/v1beta2/model.proto

BREAKING CHANGES: Structure of Model proto is changed in a backward incompatible manner.

feat!: support multiple model versions in a single asset

---

odpf/shield/v1beta1/shield.proto

As discussed, we need to have status as boolean and not string

feat: change type of status from string to bool

---

odpf/guardian/v1beta1/guardian.proto

for https://github.com/odpf/guardian/pull/331

chore(guardian): add additional fields to activity

---

odpf/shield/v1beta1/shield.proto

In favor of [ issue ](https://github.com/odpf/shield/issues/187)

feat: add get relations for an object API

---

odpf/siren/v1beta1/siren.proto

Related with https://github.com/odpf/siren/issues/163

feat(siren): add create alert with namespace api

---

odpf/siren/v1beta1/siren.proto

related with this PR https://github.com/odpf/siren/pull/167

feat(siren): add silences api

---

odpf/assets/v1beta2/table.proto

This helps in adding the schema for nested column in bigquery. 
Related to https://github.com/odpf/meteor/issues/462

feat(assets): add support to capture schema of nested columns.

---

odpf/shield/v1beta1/shield.proto

- Making the body of user create/update mandatory and adding additional slug validation rules.
- Relaxing name constraint to contain space.

fix(shield): add validation for user slug

---

odpf/guardian/v1beta1/guardian.proto

Add pagination support to ListUserApprovals & ListApprovals api

feat(guardian): add pagination in ListApprovals and ListUserApprovals

---

odpf/shield/v1beta1/shield.proto

https://github.com/odpf/shield/pull/217

feat(shield): support for oidc authentication

---

odpf/shield/v1beta1/shield.proto

Needed for https://github.com/odpf/shield/pull/221

feat(shield): additional api to list org users

---

odpf/shield/v1beta1/shield.proto

https://github.com/odpf/shield/pull/231

feat(shield): delete/disable an org/project/user/group in shield

---

odpf/shield/v1beta1/admin.proto
odpf/shield/v1beta1/shield.proto

- https://github.com/odpf/shield/pull/238

fix(shield): remove group pattern validation from admin api

---

odpf/shield/v1beta1/admin.proto
odpf/shield/v1beta1/models.proto
odpf/shield/v1beta1/shield.proto

WIP
- https://github.com/odpf/shield/pull/240

feat(shield): shield support for user-defined roles

---

odpf/shield/v1beta1/admin.proto
odpf/shield/v1beta1/models.proto
odpf/shield/v1beta1/shield.proto

This change contains breaking changes in shield API specification.

feat(shield): create permissions api

---

odpf/shield/v1beta1/admin.proto
odpf/shield/v1beta1/models.proto
odpf/shield/v1beta1/shield.proto

- Required for https://github.com/odpf/shield/pull/256

refactor(shield): remove deprecated fields

---

raystack/shield/v1beta1/admin.proto
raystack/shield/v1beta1/models.proto
raystack/shield/v1beta1/shield.proto

- Required for https://github.com/raystack/shield/pull/260

feat: add apis to list org policies, list user invitations and filter to get user groups by org

---

raystack/shield/v1beta1/admin.proto
raystack/shield/v1beta1/shield.proto

- required for https://github.com/raystack/shield/pull/270

docs: update api summary and security schemes

---

raystack/frontier/v1beta1/frontier.proto

- add bearer jwt as security defination

fix(frontier): rename shield file to frontier

---

raystack/frontier/v1beta1/admin.proto
raystack/frontier/v1beta1/frontier.proto
raystack/frontier/v1beta1/models.proto

- allow adding preferences(k/v) for org, project, user, group and platform

feat(frontier): supporting preferences for different resource types

---

raystack/frontier/v1beta1/frontier.proto

- support taking permissions with `.` in check api

feat(frontier): list project permissions with project

---

raystack/frontier/v1beta1/frontier.proto
raystack/frontier/v1beta1/models.proto

- List all groups which has viewer access to project
- List organizations with user invitations
- Role scopes

feat(frontier): list project groups

---

raystack/frontier/v1beta1/admin.proto
raystack/frontier/v1beta1/frontier.proto
raystack/frontier/v1beta1/models.proto

- DelegatedCheckout should return the applied subscription or product

feat(frontier): create payment methods in billing account

---

raystack/frontier/v1beta1/admin.proto
raystack/frontier/v1beta1/frontier.proto
raystack/frontier/v1beta1/models.proto

- allow listing all invoices
- additional subscription details

feat(frontier): allow listing all features

---

raystack/frontier/v1beta1/frontier.proto

- option to call billing api without billing account id that uses the first customer account available

feat(frontier): has trialed API

---

raystack/frontier/v1beta1/admin.proto
raystack/frontier/v1beta1/frontier.proto

Allowed to infer default enabled billing account in some of the APIs.

feat(frontier): infer default billing account v1

---

raystack/frontier/v1beta1/frontier.proto

Corresponding Frontier PR: https://github.com/raystack/frontier/pull/656

feat: add rpc signature for creating policy for projects

---

raystack/optimus/core/v1beta1/project.proto

Cleaned Cleanup Secret Message in Project Specification as it was unused.

Fix #102 : Cleanup Cleanup Secret Message in Project Specification
